name: alnabali_driver
description: Alnabali Driver App


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# version and build number for your application.
version: 1.0.0+1


environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  #cupertino_icons: ^1.0.2
  flutter_riverpod: 2.0.0-dev.9
  rxdart: ^0.27.5
  intl: ^0.17.0
  go_router: ^5.1.1
  url_strategy: ^0.2.0
  dio: ^4.0.6
  freezed_annotation: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.otf
          weight: 800
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
